version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clara_frontend
    ports:
      - "8069:8069"
    networks:
      - clara_network

  backend:
    build:
      context: ./py_backend
      dockerfile: Dockerfile
    container_name: clara_backend
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data/backend:/app/data
    ports:
      - "5001:5000"
    depends_on:
      - ollama
    networks:
      - clara_network

  n8n:
    image: n8nio/n8n:latest
    container_name: clara_n8n
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - clara_network

  ollama:
    image: ollama/ollama:latest
    container_name: clara_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - clara_network

  interpreter:
    image: clara17verse/clara-interpreter:latest
    container_name: clara_interpreter
    ports:
      - "8000:8000"
    volumes:
      - ./data/interpreter:/app/data
    networks:
      - clara_network

  comfyui:
    image: ghcr.io/comfyanonymous/comfyui:latest
    container_name: clara_comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./data/comfyui:/comfyui
    networks:
      - clara_network

networks:
  clara_network:
    driver: bridge
