version: '3.8'

services:
  # Keycloak authentication service
  clara-keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: clara_keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://clara-postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HEALTH_ENABLED=true
    command: ["start-dev"]
    depends_on:
      - clara-postgres
    networks:
      - clara_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Postgres database for Keycloak
  clara-postgres:
    image: postgres:14
    container_name: clara_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - clara_postgres_data:/var/lib/postgresql/data
    networks:
      - clara_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  clara_postgres_data:
    driver: local

networks:
  clara_network:
    driver: bridge